### ISSUE TITLE
error being generated twice per minute: list index out of range

### ISSUE THREAD

**Issue by bbrendon** [custom-components/weatheralerts#18]
```
ERROR (MainThread) [custom_components.weatheralerts.sensor] list index out of range
```

**Comment by bbrendon** [comment]
bump

**Comment by vmcosco** [comment]
Having the same issue with SAME# 026125

**Comment by ludeeus** [comment]
That usually mean that the SAMEID can not be used, try a different one

**Comment by bbrendon** [comment]
There really isn't another ID for my area. A few weeks ago there was an alert and it pulled the data fine.

**Comment by bbrendon** [comment]
...and apparently there is an issue for this upstream. https://github.com/zebpalmer/WeatherAlerts/issues/12

**Comment by ludeeus** [comment]
Really? It works when there are alerts?
Don't hold your breath, the upstream Liv looks abandoned

**Comment by bbrendon** [comment]
Yes. It’s been working okay other than the log message. The alert summary gets cut off after about three sentences.  I’ve been trying to decide if I should use this or dark sky.  Darksky has a problem where it duplicates the same alert sometimes.

**Comment by ludeeus** [comment]
That's interesting...
What sameid are you using?

**Comment by niemyjski** [comment]
I'm also having the same issue.

**Comment by niemyjski** [comment]
I'm still seeing this

**Comment by roblandry** [comment]
Here is how i fixed mine...

[Change this on Line 70](https://github.com/custom-components/weatheralerts/blob/master/custom_components/weatheralerts/sensor.py#L70)
```python
            last_event = nws.alerts[0]
```

To this:
```python
            if nws.alerts:
                last_event = nws.alerts[0]
```

The error is because there are no alerts available, and we are ASSUMING there is something in the dictionary.
