### ISSUE TITLE
summary attribute cut short

### ISSUE THREAD

**Issue by bbrendon** [custom-components/weatheralerts#20]
**Version of the custom_component**
d6a7ec3

**Describe the bug**
The summary attribute is always cut off. In order to get the full value I have to check online somewhere.  The last time I looked, the summary was 320 characters long, a few days ago it was 361 characters long. Darksky component doesn't seem to have this problem, though it has other issues.

**log**
Nothing in logs.

**Comment by ludeeus** [comment]
What SAMID are you using?
HA and this integration do not have limits for attributes, so my guess is that it's the lib that is cutting it.

**Comment by bbrendon** [comment]
> What SAMID are you using?

PM'ed you on discord.

**Comment by ludeeus** [comment]
There is nothing I can do about that in the integration.
This is the source: https://alerts.weather.gov/cap/us.php?x=0
Search for your SAMEID there, you will see that it cuts it in the source.
