### ISSUE TITLE
enough values to unpack

### ISSUE THREAD

**Issue by jmutnick** [custom-components/weatheralerts#21]
**Version of the cusom_component**
d6a7ec3

**Describe the bug**
Flooding the log with ERRORS.

**log**
[custom_components.weatheralerts.sensor] not enough values to unpack (expected 3, got 1)

**Comment by GP920** [comment]
Same. Got 3400 + errors in log in just over 24 hours.

**Comment by Photo64** [comment]
I am also getting a ton of these errors -> ERROR (SyncWorker_8) [custom_components.weatheralerts.sensor] not enough values to unpack (expected 3, got 1)

**Comment by jccshmny** [comment]
Same here.

Log Details (ERROR)
not enough values to unpack (expected 3, got 1)

**Comment by c1c9k72** [comment]
Me too.

Log Details (ERROR)
Fri Dec 13 2019 19:13:45 GMT-0500 (Eastern Standard Time)
not enough values to unpack (expected 3, got 1)

**Comment by ntilley905** [comment]
Also getting a ton of them on HASS version 103.0.

**Comment by otiswrx** [comment]
I am also getting flooded with 3000+ errors containing this error

**Comment by Photo64** [comment]
I decided to uninstall this as I had received 9645 of these errors in just 3 days. Hopefully this get resolved and I'll be able to reinstall when it's fixed.

**Comment by ludeeus** [comment]
the lib it uses tries to get info from "http://www.nws.noaa.gov/nwr/data/SameCode.txt", that address does not exist.

So I can:
- Fix the lib (if I can find a new link), wait for it to merge, then update this component.
- Deprecate the project.
- Switch to something else to get alerts, this will be a breaking change.

Thoughts?

**Comment by ludeeus** [comment]
Nevermind, you don't get a say here.
NWS has moved/are moving their API to REST and providing JSON responses.

Breaking change incoming!

**Comment by ludeeus** [comment]
<https://github.com/custom-components/weatheralerts#breaking-change>
