### ISSUE TITLE
Zones not correct

### ISSUE THREAD

**Issue by Timp103** [custom-components/weatheralerts#23]
**Version of the custom_component**
705c1d6

**Describe the bug**
Not sure if nationally but the zones in Florida do not work correctly. 8 needs to be added to whatever number the map tells you the zone is in order for it to show correctly in HA. Example Orange County should be zone 045 but 053 needs to be entered for it to work correctly.

**Comment by ludeeus** [comment]
That is out of the hands of this integration, you need to take that up with the entity that is publishing the maps.
There is contact information at the bottom of this page https://www.weather.gov/pimar/PubZone
