### ISSUE TITLE
sensor not showing in HA - No Error in Logs

### ISSUE THREAD

**Issue by Photo64** [custom-components/weatheralerts#24]
**Version of the cusom_component**
Installed: 705c1d6

**Describe the bug**
I installed weatheralerts via HACS and added the config shown below to my sensor.yaml however after restarting HA there is no sensor showing within the states page that corresponds to this. 

My understanding is I should see a sensor called sensor.010 as it defaults to the zone??

There are no errors showing in the log. I am seeing this in the log so I assume it is loading and working correctly -> "You are using a custom integration for weatheralerts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant."

- platform: weatheralerts
  state: NJ
  zone: 010

**log**
No errors are showing in log

**Comment by ludeeus** [comment]
Name of the zone, not the zone ID.

You can find it by filtering attributes in States
![img](https://cdn.discordapp.com/attachments/609399695466430465/659528238506442753/unknown.png)

**Comment by Photo64** [comment]
With this setup what should it be called? I am not seeing anything for this sensor
platform: weatheralerts
state: NJ
zone: 010

**Comment by ludeeus** [comment]
There is a bug there will push a fix shortly.
if you use `zone: 10` it should work.

And you do get an error...
```
CRITICAL (MainThread) [custom_components.weatheralerts.sensor] Compiled zone ID 'NJZ08' is not valid
```

**Comment by Photo64** [comment]
I just tried again using zone: 10 and I am seeing the "sensor.somerset" but I didn't see the error you mentioned in the log.

**Comment by ludeeus** [comment]
updated with fix/note for this issue.
