### ISSUE TITLE
"Entity Not Available"

### ISSUE THREAD

**Issue by jcqrs** [custom-components/weatheralerts#31]
I've checked the error log but I haven't seen anything related to this. I've already done the whole shebang (cleared cache, uninstalled/reinstalled component. etc). STill shows "not available."

I'm using the latest version of HACS and this component. Home Assistant ver. 103.5

**Comment by GP920** [comment]
My entity is also currently unavailable, and I see a timeout error in the logs. 0.105.1 here.

**Comment by ntilley905** [comment]
The NWS API has been having some serious uptime issues today, I'd imagine the timeouts are related.

**Comment by jcqrs** [comment]
The sensor is visible of late, but now I'm getting the following error:
"Could not update the sensor (ContentTypeError)"

**Comment by jlverhagen** [comment]
This should be fixed now, with the addition of PlatformNotReady. The weather.gov site very frequently is either slow to respond or returns various errors which will result in errors initializing the platform and updating the sensor after it is initialized. These errors aren't necessarily an indication of a total platform crash or failure, just an indication in the log that the platform didn't succeed doing what is was suppose to do at that particular time.

If it fails during initialization (during Home Assistant startup), the platform will continue to retry the initialization. After initialization, if the sensor fails to update, it will keep trying every 30 seconds (or scan_interval setting if configured).

If the problems persist with this new version of weatheralerts, open a new issue and I will investigate further.
