### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'weatheralerts'

### ISSUE THREAD

**Issue by jaydenthorup** [custom-components/weatheralerts#43]
**Version of the custom_component**
1.3
**Describe the bug**
No 'version' key in the manifest file for custom integration 'weatheralerts'
Looks like there needs to be a version key added to the manifest file.
**Log**
Logger: homeassistant.loader
Source: loader.py:802
First occurred: March 4, 2021, 8:49:51 PM (2 occurrences)
Last logged: March 4, 2021, 8:49:52 PM

No 'version' key in the manifest file for custom integration 'weatheralerts'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'weatheralerts'

**Comment by jaydenthorup** [comment]
See:
https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes

**Comment by jlverhagen** [comment]
Thanks for the report! The manifest is updated, a new release is published, and the update should now be available in HACS.
