### ISSUE TITLE
Old Weather alerts wont clear on Lovelace

### ISSUE THREAD

**Issue by tagz1979** [custom-components/weatheralerts#44]
**Version of the custom_component**
v0.1.4

**Describe the bug**
Weather Alerts Active won't clear after weather event and continues to show old expired Alerts on Lovelace

**Log**
No Errors are being reported just the keeps showing old expired alerts and Weather alerts are active keeps showing "Yes"

**Comment by JOHLC** [comment]
I believe I am seeing this as well
![image](https://user-images.githubusercontent.com/63735432/111811348-56af9780-88ad-11eb-8050-5256cba7b3d4.png)

It keeps going from 0 to 1 alerts and the 1 alert is one from 3/17 - 2 days ago

**Comment by jaydenthorup** [comment]
Mine seems to be doing this too

**Comment by jlverhagen** [comment]
I'd like to find and fix whatever is causing this issue, but I haven't seen this behavior so I'll need some more info.

Are you all using the most recent yaml package files?

Have any of you made any changes (other than the weatheralerts config details) to the yaml package files?

What version of Home Assistant are you all using?

Would you all be willing to share your state, county, and zone config details so I can track those weather alert feeds to see if there is something wrong with the alert feed?

If any of you can, grep your home-assistant.log log file for weatheralerts and send that to my email at jlverhagen@gmail.com. If you don't know what grep is, don't worry about getting this bit of info.

**Comment by tagz1979** [comment]
Are you all using the most recent yaml package files? Yes I double checked that

Have any of you made any changes (other than the weatheralerts config details) to the yaml package files? Not at all

What version of Home Assistant are you all using? The latest Core-2021-3.4

Would you all be willing to share your state, county, and zone config details so I can track those weather alert feeds to see if there is something wrong with the alert feed?

- platform: weatheralerts
  state: PA
  zone: "020"
  county: "007"

I would like to add that since the last update everything seems to be working fine now.

**Comment by bakerbug** [comment]
I'm seeing this problem as well.  I'm running the latest version, but still have a stale weather alert.  I've uninstalled and re-installed the integration, but it still has the stale data.

**Comment by jlverhagen** [comment]
> I'm seeing this problem as well. I'm running the latest version, but still have a stale weather alert. I've uninstalled and re-installed the integration, but it still has the stale data.

Can you provide your state, zone, and county configuration details? I'd like to check the json feed for your location to see if the problem is with the feed. I am suspecting the json feed is still returning old alerts instead of clearing them. I will need to see the json feed (using your state, zone, and county config details) and possibly a home-assistant.log file to confirm what is happening. If you are on a linux install and have the ability to use the grep command on the linux command line, go to the home assistant install directory where the home-assistant.log file is located and issue the command:

grep weatheralerts home-assistant.log

If you are still actively experiencing the issue, if you can copy that grep output (or at least some of the last lines of that output) and paste them in a reply here, that would be helpful.

**Comment by bakerbug** [comment]
> > I'm seeing this problem as well. I'm running the latest version, but still have a stale weather alert. I've uninstalled and re-installed the integration, but it still has the stale data.
> 
> Can you provide your state, zone, and county configuration details? I'd like to check the json feed for your location to see if the problem is with the feed. I am suspecting the json feed is still returning old alerts instead of clearing them. I will need to see the json feed (using your state, zone, and county config details) and possibly a home-assistant.log file to confirm what is happening. If you are on a linux install and have the ability to use the grep command on the linux command line, go to the home assistant install directory where the home-assistant.log file is located and issue the command:
> 
> grep weatheralerts home-assistant.log
> 
> If you are still actively experiencing the issue, if you can copy that grep output (or at least some of the last lines of that output) and paste them in a reply here, that would be helpful.

Sorry, I may not have been quick enough to respond.  After several days, the stale alert has cleared.  I've posted my configuration below.  When I see this happen again, I'll post back here.

`- platform: weatheralerts
state: AL
zone: 6
county: 89
`

* Above is properly formatted in my config.  Pasting it here removes the proper white spacing.

**Comment by bakerbug** [comment]
This issue may have resolved itself (issue in the feed?).  This past weekend I had several weather alerts, and they all cleared properly.
