### ISSUE TITLE
Alerts.weather.gov Has Changed

### ISSUE THREAD

**Issue by IIAIronWolf** [custom-components/weatheralerts#80]
The https://alerts.weather.gov website has changed and no longer goes to the list of zones and counties. I'm not entirely sure what the new link is, but my tornado alert automation recently triggered randomly for a tornado rather far from my area. I'm wondering if the website change (and probably their API or otherwise) has anything to do with it.

**Comment by cleevo989** [comment]
Are you running the latest version of Home Assistant?  My sensor is not updating.  It used to leave warnings in the log.  When I updated to the latest release of HA it does not do this anymore.  Is anyone else having the same problem?

**Comment by IIAIronWolf** [comment]
@cleevo989 yes I am the latest HA. I still get alerts but I don't know how someone else would set theirs up from scratch given the website change. I also feel as though the API change may be cause for my recent false tornado alert.

**Comment by IIAIronWolf** [comment]
@ludeeus, do you know who we can get in contact with about this potentially being abandoned (if Home Assistant has a team for that maybe?)?
I'm hopeful someone picks it up, as it was an integral part of my early warning system for hazardous weather.

**Comment by cleevo989** [comment]
I did get a special weather statement issued last night.  Which confirms my sensor is working.  I did email Jason who was a contributor/developer for weather alerts.  I have not heard back from him.  I hope someone picks it up as well.  I use weather alerts with the meteoalarm card.  I will try contacting other contributors who worked on the project.

**Comment by rugbyopera** [comment]
I just installed this integration for the first time. No problem at all with the alerts.weather.gov website. It took me right to the zones and counties. The only hiccup I had was finding the sensor (it's sensor.[zone name] most likely) - filtering my list of entities by integration would have helped me find it quicker.

**Comment by IIAIronWolf** [comment]
> I just installed this integration for the first time. No problem at all with the alerts.weather.gov website. It took me right to the zones and counties. The only hiccup I had was finding the sensor (it's sensor.[zone name] most likely) - filtering my list of entities by integration would have helped me find it quicker.
> 
> 

It appears they've either changed their website, or I totally missed that. 😑 I see it now.
Closing.
